/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ModelsAnim/Girl.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

const Girl=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./ModelsAnim/Girl.glb')
  const { actions ,names} = useAnimations(animations, group)
  
  
  //
  var ShirtMaterial = materials['mat0.028'];
  var SkinMaterial  = materials['mat0.027'];
  var ShoeMaterial = materials['mat0.018'];
  var PantMaterial = materials['mat0.017'];
  var AccessoriesMaterial= materials['mat0.016'];
  var HairMaterial= materials['mat0.015'];
  //var shirtmaterial =new THREE.MeshBasicMaterial();
  //shirtmaterial.color.setHex(0xffff00)
  
  //
  const ShirtValue=props.shirt;
  const SkinValue=props.skin;
  const ShoeValue=props.shoe;
  const PantValue=props.pant;
  const AccesoriesValue=props.Accesories;
  const HairValue=props.hair;

  //
  if(props.shirt!=null)
  {
    ShirtMaterial=new THREE.MeshBasicMaterial();
    ShirtMaterial.color.setHex(ShirtValue);
  }

  if(props.skin!=null)
  {
    SkinMaterial=new THREE.MeshBasicMaterial();
    SkinMaterial.color.setHex(SkinValue);
  }

  if(props.shoe!=null)
  {
    ShoeMaterial=new THREE.MeshBasicMaterial();
    ShoeMaterial.color.setHex(ShoeValue);
  }

  if(props.pant!=null)
  {
    PantMaterial=new THREE.MeshBasicMaterial();
    PantMaterial.color.setHex(PantValue);
  }

  if(props.Accesories!=null)
  {
    AccessoriesMaterial=new THREE.MeshBasicMaterial();
    AccessoriesMaterial.color.setHex(AccesoriesValue);
  }

  if(props.hair!=null)
  {
    HairMaterial=new THREE.MeshBasicMaterial();
    HairMaterial.color.setHex(HairValue);
  }
  
  


  

  //
  useEffect(
    ()=>{
      actions[names[0]].reset().fadeIn(1).play();
    },[]
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group name="Camera" position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]} />
        <group name="Light001" position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group name="Camera001" position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]} />
        <group name="Armature" rotation={[Math.PI / 2, 0, -1]} scale={0.01} position={[0,-2.5,0 ]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Mesh_0016rip_Mesh_0016rip_mesh0000" geometry={nodes.Mesh_0016rip_Mesh_0016rip_mesh0000.geometry} material={ShirtMaterial} skeleton={nodes.Mesh_0016rip_Mesh_0016rip_mesh0000.skeleton} />
          <skinnedMesh name="Mesh_0017rip_Mesh_0017rip_mesh0000" geometry={nodes.Mesh_0017rip_Mesh_0017rip_mesh0000.geometry} material={SkinMaterial} skeleton={nodes.Mesh_0017rip_Mesh_0017rip_mesh0000.skeleton} />
          <skinnedMesh name="Mesh_0019rip_Mesh_0019rip_mesh0000" geometry={nodes.Mesh_0019rip_Mesh_0019rip_mesh0000.geometry} material={ShoeMaterial} skeleton={nodes.Mesh_0019rip_Mesh_0019rip_mesh0000.skeleton} />
          <skinnedMesh name="Mesh_0021rip_Mesh_0021rip_mesh0000" geometry={nodes.Mesh_0021rip_Mesh_0021rip_mesh0000.geometry} material={PantMaterial} skeleton={nodes.Mesh_0021rip_Mesh_0021rip_mesh0000.skeleton} />
          <skinnedMesh name="Mesh_0023rip_Mesh_0023rip_mesh0000" geometry={nodes.Mesh_0023rip_Mesh_0023rip_mesh0000.geometry} material={AccessoriesMaterial} skeleton={nodes.Mesh_0023rip_Mesh_0023rip_mesh0000.skeleton} />
          <skinnedMesh name="Mesh_0069rip_Mesh_0069rip_mesh0000" geometry={nodes.Mesh_0069rip_Mesh_0069rip_mesh0000.geometry} material={HairMaterial} skeleton={nodes.Mesh_0069rip_Mesh_0069rip_mesh0000.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default Girl;
useGLTF.preload('/Girl.glb')
