/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ModelsAnim/Girl2.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

const Girl2=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ModelsAnim/Girl2.glb')
  const { actions ,names} = useAnimations(animations, group)
  //playground
  var ShirtMaterial = materials['mat0.086'];
  var SkinMaterial  = materials['mat0.081'];
  var ShoeMaterial = materials['mat0.085']
  var PantMaterial = materials['mat0.082'];
  var AccessoriesMaterial= materials['mat0.083'];
  var HairMaterial= materials['mat0.084'];



  const ShirtValue=props.shirt;
  const SkinValue=props.skin;
  const ShoeValue=props.shoe;
  const PantValue=props.pant;
  const AccesoriesValue=props.Accesories;
  const HairValue=props.hair;

  if(props.shirt!=null)
  {
    ShirtMaterial=new THREE.MeshBasicMaterial();
    ShirtMaterial.color.setHex(ShirtValue);
  }

  if(props.skin!=null)
  {
    SkinMaterial=new THREE.MeshBasicMaterial();
    SkinMaterial.color.setHex(SkinValue);
  }

  if(props.shoe!=null)
  {
    ShoeMaterial=new THREE.MeshBasicMaterial();
    ShoeMaterial.color.setHex(ShoeValue);
  }

  if(props.pant!=null)
  {
    PantMaterial=new THREE.MeshBasicMaterial();
    PantMaterial.color.setHex(PantValue);
  }

  if(props.Accesories!=null)
  {
    AccessoriesMaterial=new THREE.MeshBasicMaterial();
    AccessoriesMaterial.color.setHex(AccesoriesValue);
  }

  if(props.hair!=null)
  {
    HairMaterial=new THREE.MeshBasicMaterial();
    HairMaterial.color.setHex(HairValue);
  }












  //

  useEffect(()=>{
    actions[names[0]].reset().fadeIn(1).play();

  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sun" position={[0, 0, 5.15]} rotation={[2.3, 0.06, 0.01]} />
        <group name="Sun001" position={[0, 0, 5.15]} rotation={[2.29, 0.06, 0.03]} />
        <group name="Sun002" position={[0, 0, -1.9]} rotation={[-2.31, 0.08, -0.12]} />
        <group name="Armature" rotation={[Math.PI / 2, 0,-1]} scale={0.008} position={[0,-3,0]}>
          <primitive object={nodes.mixamorigHips} />
          <ambientLight intensity={1}/>
          <ambientLight intensity={5} position={[0,-2,0]}/>
          <pointLight intensity={1} position={[0,10,0]}/>
          <skinnedMesh name="Mesh_0027rip" geometry={nodes.Mesh_0027rip.geometry} material={ShoeMaterial} skeleton={nodes.Mesh_0027rip.skeleton} />
          <skinnedMesh name="Mesh_0036rip" geometry={nodes.Mesh_0036rip.geometry} material={SkinMaterial} skeleton={nodes.Mesh_0036rip.skeleton} />
          <skinnedMesh name="Mesh_0053rip" geometry={nodes.Mesh_0053rip.geometry} material={PantMaterial} skeleton={nodes.Mesh_0053rip.skeleton} />
          <skinnedMesh name="Mesh_0145rip" geometry={nodes.Mesh_0145rip.geometry} material={HairMaterial} skeleton={nodes.Mesh_0145rip.skeleton} />
          <skinnedMesh name="Mesh_0632rip" geometry={nodes.Mesh_0632rip.geometry} material={ShirtMaterial} skeleton={nodes.Mesh_0632rip.skeleton} />
          <skinnedMesh name="Mesh_0650rip" geometry={nodes.Mesh_0650rip.geometry} material={AccessoriesMaterial} skeleton={nodes.Mesh_0650rip.skeleton} />
        </group>
        <group name="Sun003" position={[0, 0, 5.15]} rotation={[2.29, 0.06, 0.03]} />
        <group name="Point" position={[-0.37, 5.41, 0.46]} />
      </group>
    </group>
  )
}
export default Girl2;
useGLTF.preload('/Girl2.glb')
