/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ModelsAnim/Mafia.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'





 const Mafia=(props) =>{
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ModelsAnim/Mafia.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names)

  //play hub
  var ShirtMaterial = materials['mat0.053'];
  var SkinMaterial  = materials['mat0.056'];
  var ShoeMaterial = materials['mat0.055'];
  var PantMaterial = materials['mat0.054'];
  var AccessoriesMaterial= materials['mat0.052'];
  var HairMaterial= materials['mat0.051'];




  const ShirtValue=props.shirt;
  const SkinValue=props.skin;
  const ShoeValue=props.shoe;
  const PantValue=props.pant;
  const AccesoriesValue=props.Accesories;
  const HairValue=props.hair;



  if(props.shirt!=null)
  {
    ShirtMaterial=new THREE.MeshBasicMaterial();
    ShirtMaterial.color.setHex(ShirtValue);
  }

  if(props.skin!=null)
  {
    SkinMaterial=new THREE.MeshBasicMaterial();
    SkinMaterial.color.setHex(SkinValue);
  }

  if(props.shoe!=null)
  {
    ShoeMaterial=new THREE.MeshBasicMaterial();
    ShoeMaterial.color.setHex(ShoeValue);
  }

  if(props.pant!=null)
  {
    PantMaterial=new THREE.MeshBasicMaterial();
    PantMaterial.color.setHex(PantValue);
  }

  if(props.Accesories!=null)
  {
    AccessoriesMaterial=new THREE.MeshBasicMaterial();
    AccessoriesMaterial.color.setHex(AccesoriesValue);
  }

  if(props.hair!=null)
  {
    HairMaterial=new THREE.MeshBasicMaterial();
    HairMaterial.color.setHex(HairValue);
  }























//dont touch here  by g1 -devloper --hAI ---highest mental state
  useEffect(()=>
  {
    actions[names[2]].reset().fadeIn(0.5).play();
    actions[names[0]].reset().fadeIn(0.5).play();
    
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group name="Point" position={[-0.98, 4.76, 0.27]} />
        <group name="Sun" position={[-0.79, 6.55, 3.59]} rotation={[0.73, -0.25, 0.08]} />
        <group name="Sun001" position={[-0.79, 6.55, -4.84]} rotation={[-0.61, -0.44, 0.17]} />
        <group name="Sun002" position={[-0.79, 6.55, 3.59]} rotation={[0.73, -0.25, 0.08]} />
        <group name="Sun003" position={[-0.79, 6.55, -4.84]} rotation={[-0.61, -0.44, 0.17]} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01} position={[0,-3,0]}>
          <primitive object={nodes.mixamorigHips} />
          <ambientLight intensity={1}/>
          <skinnedMesh name="Mesh_0015rip_Mesh_0015rip_mesh0000001" geometry={nodes.Mesh_0015rip_Mesh_0015rip_mesh0000001.geometry} material={SkinMaterial} skeleton={nodes.Mesh_0015rip_Mesh_0015rip_mesh0000001.skeleton} />
          <skinnedMesh name="Mesh_0018rip_Mesh_0018rip_mesh0000001" geometry={nodes.Mesh_0018rip_Mesh_0018rip_mesh0000001.geometry} material={ShoeMaterial} skeleton={nodes.Mesh_0018rip_Mesh_0018rip_mesh0000001.skeleton} />
          <skinnedMesh name="Mesh_0019rip_Mesh_0019rip_mesh0000001" geometry={nodes.Mesh_0019rip_Mesh_0019rip_mesh0000001.geometry} material={PantMaterial} skeleton={nodes.Mesh_0019rip_Mesh_0019rip_mesh0000001.skeleton} />
          <skinnedMesh name="Mesh_0021rip_Mesh_0021rip_mesh0000001" geometry={nodes.Mesh_0021rip_Mesh_0021rip_mesh0000001.geometry} material={ShirtMaterial} skeleton={nodes.Mesh_0021rip_Mesh_0021rip_mesh0000001.skeleton} />
          <skinnedMesh name="Mesh_0023rip_Mesh_0023rip_mesh0000001" geometry={nodes.Mesh_0023rip_Mesh_0023rip_mesh0000001.geometry} material={AccessoriesMaterial} skeleton={nodes.Mesh_0023rip_Mesh_0023rip_mesh0000001.skeleton} />
          <skinnedMesh name="Mesh_0036rip_Mesh_0036rip_mesh0000001" geometry={nodes.Mesh_0036rip_Mesh_0036rip_mesh0000001.geometry} material={HairMaterial} skeleton={nodes.Mesh_0036rip_Mesh_0036rip_mesh0000001.skeleton} />
          <skinnedMesh name="Mesh_0042rip_Mesh_0042rip_mesh0000001" geometry={nodes.Mesh_0042rip_Mesh_0042rip_mesh0000001.geometry} material={materials['mat0.050']} skeleton={nodes.Mesh_0042rip_Mesh_0042rip_mesh0000001.skeleton} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[-0.33, -700.97, 0.93]} scale={0.07} />
      </group>
    </group>
  )
}
export default Mafia;

useGLTF.preload('/Mafia.glb')
