/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ModelsAnim/Redtshirt.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from'three'

const RedShirt=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ModelsAnim/Redtshirt.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names);
  //
  var ShirtMaterial = materials['mat0.067'];
  var SkinMaterial  = materials['mat0.064'];
  var ShoeMaterial = materials['mat0.068'];
  var PantMaterial = materials['mat0.066'];
  var AccessoriesMaterial= materials['mat0.063'];
  var HairMaterial= materials['mat0.065'];

  const ShirtValue=props.shirt;
  const SkinValue=props.skin;
  const ShoeValue=props.shoe;
  const PantValue=props.pant;
  const AccesoriesValue=props.Accesories;
  const HairValue=props.hair;

  if(props.shirt!=null)
  {
    ShirtMaterial=new THREE.MeshBasicMaterial();
    ShirtMaterial.color.setHex(ShirtValue);
  }

  if(props.skin!=null)
  {
    SkinMaterial=new THREE.MeshBasicMaterial();
    SkinMaterial.color.setHex(SkinValue);
  }

  if(props.shoe!=null)
  {
    ShoeMaterial=new THREE.MeshBasicMaterial();
    ShoeMaterial.color.setHex(ShoeValue);
  }

  if(props.pant!=null)
  {
    PantMaterial=new THREE.MeshBasicMaterial();
    PantMaterial.color.setHex(PantValue);
  }

  if(props.Accesories!=null)
  {
    AccessoriesMaterial=new THREE.MeshBasicMaterial();
    AccessoriesMaterial.color.setHex(AccesoriesValue);
  }

  if(props.hair!=null)
  {
    HairMaterial=new THREE.MeshBasicMaterial();
    HairMaterial.color.setHex(HairValue);
  }














  //

  useEffect(()=>
  {
    actions[names[6]].reset().fadeIn(0.5).play();

  },[]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sun" position={[0, 0, 6.4]} rotation={[2.55, -0.24, 0]} />
        <group name="Sun001" position={[0.04, -0.4, -4.46]} rotation={[-2.56, 0.79, 0.02]} />
        <group name="Sun002" position={[0.05, 13.39, -3.15]} rotation={[-0.42, -0.2, -0.04]} />
        <group name="Sun003" position={[0.3, 13.57, 3.75]} rotation={[0.31, 0.04, -0.03]} />
        <group name="Sun004" position={[-0.33, -700.97, 0.93]} scale={0.07} />
        <group name="Sun005" position={[-0.33, -700.97, 0.93]} scale={0.07} />
        <group name="Sun006" position={[-0.33, -700.97, 0.93]} scale={0.07} />
        <group name="Sun007" position={[-0.33, -700.97, 0.93]} scale={0.07} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.006} position={[0,-3,0]}>
          <primitive object={nodes.mixamorigHips} />
          <ambientLight intensity={2}/>
          <skinnedMesh name="Mesh_0014rip" geometry={nodes.Mesh_0014rip.geometry} material={ShirtMaterial} skeleton={nodes.Mesh_0014rip.skeleton} />
          <skinnedMesh name="Mesh_0015rip" geometry={nodes.Mesh_0015rip.geometry} material={AccessoriesMaterial} skeleton={nodes.Mesh_0015rip.skeleton} />
          <skinnedMesh name="Mesh_0017rip" geometry={nodes.Mesh_0017rip.geometry} material={ShoeMaterial} skeleton={nodes.Mesh_0017rip.skeleton} />
          <skinnedMesh name="Mesh_0019rip" geometry={nodes.Mesh_0019rip.geometry} material={SkinMaterial} skeleton={nodes.Mesh_0019rip.skeleton} />
          <skinnedMesh name="Mesh_0021rip" geometry={nodes.Mesh_0021rip.geometry} material={PantMaterial} skeleton={nodes.Mesh_0021rip.skeleton} />
          <skinnedMesh name="Mesh_0035rip" geometry={nodes.Mesh_0035rip.geometry} material={HairMaterial} skeleton={nodes.Mesh_0035rip.skeleton} />
        </group>
        <group name="Point" position={[0.81, 7.38, 1.08]} />
      </group>
    </group>
  )
}

export default RedShirt;
useGLTF.preload('/Redtshirt.glb')
