/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ModelsAnim/TatooBoy.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const TatooBoy=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ModelsAnim/TatooBoy.glb')
  const { actions,names} = useAnimations(animations, group)
  useEffect(()=>
  {
    actions[names[0]].reset().fadeIn(1).play();
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.015} position={[-10,-4,0]}>
          <primitive object={nodes.mixamorigHips} />
          <ambientLight intensity={2}/>
          <skinnedMesh name="Mesh_0016rip" geometry={nodes.Mesh_0016rip.geometry} material={materials['mat0.038']} skeleton={nodes.Mesh_0016rip.skeleton} />
          <skinnedMesh name="Mesh_0017rip" geometry={nodes.Mesh_0017rip.geometry} material={materials['mat0.037']} skeleton={nodes.Mesh_0017rip.skeleton} />
          <skinnedMesh name="Mesh_0019rip" geometry={nodes.Mesh_0019rip.geometry} material={materials['Material.002body.001']} skeleton={nodes.Mesh_0019rip.skeleton} />
          <skinnedMesh name="Mesh_0021rip" geometry={nodes.Mesh_0021rip.geometry} material={materials['mat0.042']} skeleton={nodes.Mesh_0021rip.skeleton} />
          <skinnedMesh name="Mesh_0023rip" geometry={nodes.Mesh_0023rip.geometry} material={materials['mat0.041']} skeleton={nodes.Mesh_0023rip.skeleton} />
          <skinnedMesh name="Mesh_0025rip" geometry={nodes.Mesh_0025rip.geometry} material={materials['handband.001']} skeleton={nodes.Mesh_0025rip.skeleton} />
          <skinnedMesh name="Mesh_0041rip" geometry={nodes.Mesh_0041rip.geometry} material={materials['mat0.040']} skeleton={nodes.Mesh_0041rip.skeleton} />
          <skinnedMesh name="Mesh_0044rip" geometry={nodes.Mesh_0044rip.geometry} material={materials['mat0.039']} skeleton={nodes.Mesh_0044rip.skeleton} />
        </group>
      </group>
    </group>
  )
}


export default TatooBoy;
useGLTF.preload('/TatooBoy.glb')
