/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ModelsAnim/Villan.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Villan=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ModelsAnim/Villan.glb')
  const { actions,names } = useAnimations(animations, group)
  useEffect(
    ()=>
    {
      actions[names[0]].reset().fadeIn(1).play();
    },[]
  )
  return (
    <group ref={group} {...props} dispose={null}>
    
        

        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.02} position={[1,-2,1]}>
          <primitive object={nodes.mixamorigHips} />
          <ambientLight intensity={0.5}/>
          <skinnedMesh name="00000003" geometry={nodes['00000003'].geometry} material={materials['00000003_0.002']} skeleton={nodes['00000003'].skeleton} />
          <skinnedMesh name="00000004" geometry={nodes['00000004'].geometry} material={materials['00000004_0.002']} skeleton={nodes['00000004'].skeleton} />
          <group name="00000008">
            <skinnedMesh name="00000008004" geometry={nodes['00000008004'].geometry} material={materials['00000008_0.002']} skeleton={nodes['00000008004'].skeleton} />
            <skinnedMesh name="00000008004_1" geometry={nodes['00000008004_1'].geometry} material={materials['00000008_1.002']} skeleton={nodes['00000008004_1'].skeleton} />
            <skinnedMesh name="00000008004_2" geometry={nodes['00000008004_2'].geometry} material={materials['00000008_2.002']} skeleton={nodes['00000008004_2'].skeleton} />
            <skinnedMesh name="00000008004_3" geometry={nodes['00000008004_3'].geometry} material={materials['00000008_3.002']} skeleton={nodes['00000008004_3'].skeleton} />
            <skinnedMesh name="00000008004_4" geometry={nodes['00000008004_4'].geometry} material={materials['00000008_4.002']} skeleton={nodes['00000008004_4'].skeleton} />
          </group>
          <skinnedMesh name="00000008001" geometry={nodes['00000008001'].geometry} material={materials['00000008_0.002']} skeleton={nodes['00000008001'].skeleton} />
          <skinnedMesh name="0000000b" geometry={nodes['0000000b'].geometry} material={materials['0000000b_0.002']} skeleton={nodes['0000000b'].skeleton} />
          <skinnedMesh name="0000000c" geometry={nodes['0000000c'].geometry} material={materials['0000000c_0.002']} skeleton={nodes['0000000c'].skeleton} />
        </group>
      
    </group>
  )
}
export default Villan;

useGLTF.preload('/Villan.glb')
